version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
      - path: internal/domain/mocks/
        linters:
          - errcheck
          - gosimple
          - govet
          - ineffassign
          - staticcheck
          - unused
          - misspell
          - unconvert
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kenanabbak/notification-management-api

run:
  timeout: 5m
